# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ear_tag', models.CharField(blank=True, max_length=30)),
                ('ear_tag_color', models.CharField(choices=[('r', 'Red'), ('w', 'White'), ('y', 'Yellow'), ('g', 'Green'), ('b', 'Blue'), ('a', 'Gray'), ('c', 'Cyan'), ('k', 'Black')], default='w', max_length=1)),
                ('birth_date_utc', models.DateTimeField(blank=True, null=True, verbose_name='born')),
                ('main_picture', models.ImageField(blank=True, upload_to=b'')),
                ('quality', models.CharField(blank=True, choices=[('e', 'E'), ('e-', 'E-'), ('e+', 'E+'), ('u', 'U'), ('u-', 'U-'), ('u+', 'U+'), ('r', 'R'), ('r-', 'R-'), ('r+', 'R+'), ('o', 'O'), ('o-', 'O-'), ('o+', 'O+'), ('p', 'P'), ('p-', 'P-'), ('p+', 'P+')], max_length=2)),
                ('fat_percentage', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('m', 'Ram'), ('f', 'Ewe')], max_length=1)),
                ('dead', models.DateTimeField(blank=True, null=True, verbose_name='death')),
                ('removed', models.DateTimeField(blank=True, null=True, verbose_name='removed')),
                ('origin', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_father', to='sau.Sheep')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_mother', to='sau.Sheep')),
            ],
        ),
    ]
