# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sau', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='ear_tag_color',
            field=models.CharField(choices=[('r', 'Red'), ('w', 'White'), ('y', 'Yellow'), ('g', 'Green'), ('b', 'Blue'), ('a', 'Gray'), ('c', 'Cyan'), ('k', 'Black')], default='w', max_length=1),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='father',
            field=models.ManyToManyField(blank=True, related_name='_sheep_father_+', to='sau.Sheep'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='mother',
            field=models.ManyToManyField(blank=True, related_name='_sheep_mother_+', to='sau.Sheep'),
        ),
    ]
