# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=25)),
                ('date_utc', models.DateTimeField(blank=True, null=True, verbose_name='given')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='dose',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sau.Medicine'),
        ),
        migrations.AddField(
            model_name='dose',
            name='sheep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sau.Sheep'),
        ),
    ]
