# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-27 18:20
from __future__ import unicode_literals

from django.db import migrations, models
from django.template.defaultfilters import slugify


class Migration(migrations.Migration):

    def create_slug_from_name(apps, schema_editor):
        Sheep = apps.get_model('sau', 'Sheep')
        for sheep in Sheep.objects.all():
            sheep.slug = slugify(sheep.name)
            sheep.save()

    dependencies = [
        ('sau', '0002_auto_20171126_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='slug',
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.RunPython(create_slug_from_name),
    ]
