# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sau', '0002_auto_20171119_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheep',
            name='father',
        ),
        migrations.RemoveField(
            model_name='sheep',
            name='mother',
        ),
        migrations.AddField(
            model_name='sheep',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sau.Sheep'),
        ),
    ]
