# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sau', '0003_auto_20171119_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_father', to='sau.Sheep'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_mother', to='sau.Sheep'),
        ),
    ]
