# Generated by Django 2.0 on 2017-12-14 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_default_farm(apps, schema_editor):
    Farm = apps.get_model('sau', 'Farm')
    f = Farm(name='Drange Gård')
    f.save()

    Sheep = apps.get_model('sau', 'Sheep')
    for sheep in Sheep.objects.all().iterator():
        sheep.farm = f
        sheep.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sau', '0003_auto_20171127_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('farmers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sheep',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sau.Farm'),
        ),
        migrations.RunPython(create_default_farm),
        migrations.AlterField(
            model_name='sheep',
            name='farm',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, to='sau.Farm'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=40),
        ),
    ]
