# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sau', '0004_auto_20171119_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sheep',
            name='origin',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='birth_date_utc',
            field=models.DateTimeField(blank=True, null=True, verbose_name='born'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='fat_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_father', to='sau.Sheep'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='main_picture',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='a_mother', to='sau.Sheep'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
