# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sau', '0005_auto_20171123_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='ear_tag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
