# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sau', '0006_auto_20171123_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='born'),
        ),
    ]
